import { ClarificationQuestion } from '@tickets/domain/tech-spec/TechSpecGenerator';

/**
 * QuestionRound - Value Object encapsulating a single round of clarification questions
 *
 * Represents one iteration in the 3-round maximum iterative refinement workflow.
 * Each round captures:
 * - Generated questions specific to this round
 * - User answers to those questions
 * - Codebase analysis context at time of generation (for audit trail and re-analysis)
 * - Timestamps for tracking progress
 * - User decision to skip remaining rounds
 *
 * The round number (1-3) enforces a hard maximum on refinement iterations.
 */
export interface QuestionRound {
  /**
   * Round sequence number (1, 2, or 3)
   * Enforces maximum 3 refinement rounds per ticket
   */
  roundNumber: 1 | 2 | 3;

  /**
   * Clarification questions generated by agent for this round
   * Can be 0-N questions (agent-driven, no hard per-round limit)
   */
  questions: ClarificationQuestion[];

  /**
   * User answers to questions in this round
   * Maps question ID → answer value(s)
   * Empty until user completes round
   */
  answers: Record<string, string | string[]>;

  /**
   * Timestamp when questions were generated by agent
   */
  generatedAt: Date;

  /**
   * Timestamp when user completed answering this round
   * Null until round is completed
   */
  answeredAt: Date | null;

  /**
   * JSON snapshot of codebase context at time of generation
   * Used for audit trail and to provide context during re-analysis
   * Format: JSON string representation of CodebaseContext
   */
  codebaseContext: string;

  /**
   * Flag indicating user manually skipped remaining rounds
   * If true, no further questions will be asked even if Round < 3
   */
  skippedByUser: boolean;
}
