import { Injectable, CanActivate, ExecutionContext, UnauthorizedException, Logger } from '@nestjs/common';
import * as jwt from 'jsonwebtoken';
import { FirebaseService } from '../../infrastructure/firebase/firebase.config';

/**
 * Session JWT payload — generated by SessionsController when starting a
 * Cloud Develop session. Signed with JWT_INVITE_SECRET (HS256).
 */
interface SessionJwtPayload {
  sessionId: string;
  teamId: string;
  ticketId: string;
  type: 'session';
}

@Injectable()
export class FirebaseAuthGuard implements CanActivate {
  private readonly logger = new Logger(FirebaseAuthGuard.name);

  constructor(private readonly firebaseService: FirebaseService) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const request = context.switchToHttp().getRequest();
    const authHeader = request.headers.authorization;

    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      throw new UnauthorizedException('No authorization token provided');
    }

    const token = authHeader.split('Bearer ')[1];

    // 1. Try Firebase ID token first (web UI, CLI)
    try {
      const decodedToken = await this.firebaseService.getAuth().verifyIdToken(token);
      request.user = decodedToken;
      return true;
    } catch {
      // Firebase verification failed — fall through to session JWT
    }

    // 2. Try session JWT (sandbox MCP server calling back to Forge API)
    try {
      const secret = process.env.JWT_INVITE_SECRET;
      if (!secret) {
        throw new UnauthorizedException('Server misconfiguration: JWT_INVITE_SECRET not set');
      }

      const payload = jwt.verify(token, secret, { algorithms: ['HS256'] }) as SessionJwtPayload;

      if (payload.type !== 'session') {
        throw new UnauthorizedException('Invalid token type');
      }

      // Attach a synthetic user object so downstream guards/controllers work.
      // The uid is a namespaced value that can't collide with real Firebase UIDs.
      request.user = {
        uid: `session:${payload.sessionId}`,
        sessionId: payload.sessionId,
        teamId: payload.teamId,
        ticketId: payload.ticketId,
        isSessionToken: true,
      };

      return true;
    } catch (error: any) {
      if (error instanceof UnauthorizedException) throw error;
      this.logger.warn(`Both Firebase and session JWT verification failed: ${error.message}`);
      throw new UnauthorizedException('Invalid or expired token');
    }
  }
}
