import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy — forge',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-[#e8e8e8]">
      <div className="max-w-2xl mx-auto px-6 py-16 space-y-8">
        <div>
          <Link href="/login" className="text-sm text-[#71717a] hover:text-[#a1a1aa]">
            &larr; Back to login
          </Link>
          <h1 className="text-2xl font-semibold text-white mt-6">Privacy Policy</h1>
          <p className="text-sm text-[#71717a] mt-2">Last updated: March 13, 2026</p>
        </div>

        <section className="space-y-4 text-sm leading-relaxed text-[#a1a1aa]">
          <h2 className="text-base font-medium text-white">1. What We Collect</h2>

          <h3 className="text-sm font-medium text-[#d4d4d8]">Account Information</h3>
          <p>
            When you sign in with Google or GitHub, we receive your name, email address, and
            profile photo from the OAuth provider. We use this to create and identify your account.
          </p>

          <h3 className="text-sm font-medium text-[#d4d4d8]">Repository Data</h3>
          <p>
            When you connect a GitHub repository, forge reads file trees, configuration files, and
            select source files through the GitHub API.{' '}
            <strong className="text-white">
              forge never clones your repository and does not store raw source code.
            </strong>{' '}
            File contents are processed in-memory, sent to our AI provider for analysis, and
            discarded after the operation completes. Only the generated outputs (specifications,
            analysis summaries) are persisted.
          </p>

          <h3 className="text-sm font-medium text-[#d4d4d8]">Usage Data</h3>
          <p>
            We collect anonymized product analytics (page views, feature usage, error rates) via
            PostHog to understand how the product is used and improve it. We also track token usage
            per team for quota enforcement.
          </p>

          <h3 className="text-sm font-medium text-[#d4d4d8]">Generated Content</h3>
          <p>
            Technical specifications, clarification questions, analysis results, and other outputs
            generated by forge are stored in your team&apos;s workspace on our infrastructure
            (Google Cloud / Firebase).
          </p>

          <h2 className="text-base font-medium text-white mt-8">2. How We Use Your Data</h2>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>To provide, maintain, and improve the forge service.</li>
            <li>To enforce usage limits and prevent abuse.</li>
            <li>To send transactional communications (account setup, critical service updates).</li>
            <li>To understand usage patterns and improve the product (anonymized analytics only).</li>
          </ul>
          <p>
            We do <strong className="text-white">not</strong> sell your data. We do{' '}
            <strong className="text-white">not</strong> use your code or generated content to
            train AI models. We do <strong className="text-white">not</strong> share personal
            data with advertisers.
          </p>

          <h2 className="text-base font-medium text-white mt-8">3. Third-Party Services</h2>
          <p>forge relies on the following third-party services to operate:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>
              <strong className="text-white">Anthropic</strong> — AI model provider. Source file
              contents are sent to Anthropic&apos;s API for analysis during spec generation.
              Anthropic&apos;s usage policy prohibits them from training on API inputs. See{' '}
              <a
                href="https://www.anthropic.com/privacy"
                target="_blank"
                rel="noopener noreferrer"
                className="text-white underline underline-offset-2"
              >
                Anthropic&apos;s Privacy Policy
              </a>.
            </li>
            <li>
              <strong className="text-white">Firebase / Google Cloud</strong> — Authentication,
              database, and hosting infrastructure.
            </li>
            <li>
              <strong className="text-white">GitHub</strong> — OAuth authentication and repository
              API access (read-only, per your authorization).
            </li>
            <li>
              <strong className="text-white">PostHog</strong> — Product analytics (anonymized
              usage data, no source code).
            </li>
          </ul>

          <h2 className="text-base font-medium text-white mt-8">4. Data Retention</h2>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>
              <strong className="text-white">Source code:</strong> Never stored. Processed
              in-memory and discarded after each analysis operation.
            </li>
            <li>
              <strong className="text-white">Generated content:</strong> Retained as long as your
              team&apos;s workspace exists. You can delete individual tickets at any time.
            </li>
            <li>
              <strong className="text-white">Account data:</strong> Retained while your account is
              active. Contact us to request deletion.
            </li>
            <li>
              <strong className="text-white">Analytics:</strong> Anonymized usage data is retained
              for up to 12 months.
            </li>
          </ul>

          <h2 className="text-base font-medium text-white mt-8">5. Security</h2>
          <p>
            We use industry-standard security measures including encrypted connections (TLS),
            encrypted OAuth tokens at rest, Firebase security rules for data isolation between
            teams, and scoped API access. However, no system is 100% secure, and we cannot
            guarantee absolute security.
          </p>

          <h2 className="text-base font-medium text-white mt-8">6. Your Rights</h2>
          <p>You have the right to:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Access the data we hold about you.</li>
            <li>Delete your account and associated data.</li>
            <li>Revoke GitHub OAuth access at any time from your GitHub settings.</li>
            <li>Opt out of analytics by using a browser ad blocker (our analytics proxy respects opt-out signals).</li>
          </ul>

          <h2 className="text-base font-medium text-white mt-8">7. Alpha Considerations</h2>
          <p>
            During the alpha period, our data practices may evolve as the product matures. We will
            update this policy accordingly. Data created during alpha is handled with the same care
            as production data, but we cannot guarantee its preservation if the service changes
            significantly.
          </p>

          <h2 className="text-base font-medium text-white mt-8">8. Changes to This Policy</h2>
          <p>
            We may update this privacy policy from time to time. We will notify users of material
            changes through the application or via email. Continued use after changes constitutes
            acceptance.
          </p>

          <h2 className="text-base font-medium text-white mt-8">9. Contact</h2>
          <p>
            For privacy questions or data requests, contact us at{' '}
            <a href="mailto:ticketsforge@gmail.com" className="text-white underline underline-offset-2 hover:text-[#e8e8e8]">
              ticketsforge@gmail.com
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
